using './main.bicep'

param namePrefix = 'kaboomprod'
param webAppName = 'kaboom-prod-example'
param postgresServerName = 'kaboom-prod-example-pg'
param postgresAdminLogin = 'kaboomadmin'
param postgresAdminPassword = 'ReplaceWithAStrongPassword!'
param publicOrigin = 'https://kaboom-prod-example.azurewebsites.net'
param googleClientId = ''
param googleClientSecret = ''
param githubRepositoryOwner = 'your-github-org-or-user'
param githubRepositoryName = 'kaboom'
param githubBranch = 'main'
param developerIpAddress = ''
